spring:
  application:
    name: back
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=mock-test
    username: postgres
    password: '123456'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true