spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
        shutdown-timeout: 100ms
  application:
    name: back
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=mock-test
    username: postgres
    password: '123456'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true